source 'https://cdn.cocoapods.org/'
platform :ios, '12.0'

target 'UnityFramework' do
  pod 'Firebase/Auth', '9.1.0'
  pod 'Firebase/Core', '9.1.0'
  pod 'Firebase/Database', '9.1.0'
  pod 'Firebase/Storage', '9.1.0'
end
target 'Unity-iPhone' do
end
use_frameworks! :linkage => :static
